name: Ejecutar pruebas Jest

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test
